# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0002_proyecto_legislatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='legislatura',
            field=models.IntegerField(),
        ),
    ]
