# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0003_auto_20160903_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='congresistas_ascii',
            field=models.TextField(blank=True, help_text='Congress data is not 100% consistent in names and in some projects the names come with full accents or sometimes some are missing. It is better to compare them by using the ascii form of their names.'),
        ),
    ]
