# Generated by Django 3.0.8 on 2020-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0004_proyecto_congresistas_ascii'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='legislatura_name',
            field=models.TextField(null=True),
        ),
    ]
